### ISSUE TITLE
iban returns nill

### ISSUE THREAD

**Issue by fengzeyan** [BANKEX/web3swift#137]
let ethAddress = EthereumAddress("0x9e87448bff240dace7cea2e90670b8d6c2c73a6e")!
        let native = IBAN(ethAddress)
        let iban = native?.iban
        return iban;

I found code at IBAN.swift  `        guard base36EncodedString.count <= 30 else {return nil}
`  it returns nil .   any help?

**Comment by shamatar** [comment]
It’s indeed an expected behavior, not every Ethereum address can be serialized to IBAN if you follow the standard (it should start with 0x0 or 0x03 or lower, don’t remember exactly). There is an extension but it wasn’t implemented due to other priorities.

Sincerely, Alex

________________________________

**Comment by fengzeyan** [comment]
But web3.js  could serialized it , so why?
