### ISSUE TITLE
EventParserResult.transactionReceipt is always null

### ISSUE THREAD

**Issue by wingsofovnia** [BANKEX/web3swift#149]
An event returned by `contract.getIndexedEvents` always has `transactionReceipt` ~ nil.
https://github.com/BANKEX/web3swift/blob/609ee895a18f1310839d5fb0c172438731c86b5c/web3swift/Web3/Classes/Web3%2BEventParser.swift#L134
It's reqired to have this data for many cases e.g. for getting block number where the event reside in.

The strange thing is that debugger shows that the value is set:
<img width="584" alt="2018-06-17 14 17 08" src="https://user-images.githubusercontent.com/5632544/41507736-3839533c-7239-11e8-8f4c-8df2c34a016b.png">
while the getter returns nil:
<img width="574" alt="2018-06-17 14 17 34" src="https://user-images.githubusercontent.com/5632544/41507737-40a1577c-7239-11e8-9c06-5540df5c0984.png">

Are there any other ways to fetch event's block number?

**Comment by shamatar** [comment]
Hello @wingsofovnia 

Let me investigate

**Comment by shamatar** [comment]
@wingsofovnia 

From 0.9.0 event parsing result will return full event log as result.eventLog. In addition you can explicitly specify new option in getIndexedEvents call
```
joinWithReceipts: Bool = false
```
to get receipts in addition to event logs when receipts are not fetched during the internal processing. 

For example:
- getIndexedEvents calls external node to do all the filtering and just parses the returned event logs. So to get receipts you have to specify an option.
- parseTransactionByHash fetches a receipt from external node and than parses it for all events, so you get the receipt automatically.

Release of 0.9.0 is going to happen in the next two days after I bind all existing synchronous functions to use of promises instead of NSOperations

Sincerely, Alex

**Comment by wingsofovnia** [comment]
Hi @shamatar 

Thank you for a prompt reply!

Plase correct me if I'm wrong: when 0.9.0 arrive, I will be able to use `getIndexedEventsPromise` with `joinWithReceipts = true` and `transactionReceipt` will get populated with expected values.

**Comment by shamatar** [comment]
@wingsofovnia 

0.9.0 is out and by default you get an ```EventLog``` object inside the ```EventParserResult```. ```EventLog``` contains transaction hash, index, block number and block hash by itself. Although if you want transaction receipt (for input data, sender, value, etc.) you can specify ```joinWithReceipts = true ```

Sincerely, Alex

**Comment by shamatar** [comment]
Fixed in 0.9.0
