### ISSUE TITLE
V value not handled correctly

### ISSUE THREAD

**Issue by James-Sangalli** [BANKEX/web3swift#167]
Hi,

I noticed that when passing in a signature that has the recid as either 27,28, 29 or 30, the library crashes stating it is not the recid - 27 i.e. 0,1,2,3. At the very least the library should be able to handle both types and the default is to provide the v value as 27 and above not v - 27. 

Cheers

**Comment by shamatar** [comment]
Hello @James-Sangalli 

Bindings to secp256k1 were not originally supposed to be used for anything other than transaction signing and handing different ranges of V values (0-3, 27-30, or 35+) was on behalf of transaction class itself. Due to the legacy of some old Ethereum implementation I've added a protection to have either v or v-27 (so, 0-3 range for V) upon unmarshalling a raw signature , but function that marshalles R|S|V to bytes will return V value in a range of 0-3 only.

If you have some custom scenario - please post it here for my understanding.

Sincerely, Alex

**Comment by James-Sangalli** [comment]
hi @shamatar 

I am using a custom version here: https://github.com/alpha-wallet/web3swift.git (due to dependency conflicts)

When I use ecrecover, it will only accept v -27, was this tolerance added in a later version?

**Comment by James-Sangalli** [comment]
When v is 1c or 1b in hex and submitted I get back the error that v must be less than 3

**Comment by shamatar** [comment]
You should check against master branch after 169 PR

________________________________
