### ISSUE TITLE
Transaction Receipt

### ISSUE THREAD

**Issue by CrisESC93** [BANKEX/web3swift#21]
Hello

Thanks for sharing this great update, just I have some doubts and I hope you can help me.

First, in our private node the response that give when we request for the receipt doesn't has the parameter `status` (this crash the app), so for solve this (temporally) I changed a little the library adding a new `enum` (in this case `unknown`) and change the `guard let` for `if let`, but you consider the response from the node had to be have this parameter (`status`)?

Second, in the moment when I create, sign and send a transaction the user maybe wants their receipt (waiting for it, getting a notification or in a transaction history) but the method (`getTransactionReceipt`) gives the response in a synchronus way and it's probably the receipt was `null`. So, there is a some way to get the response working with asynchrony like a promise (maybe using delegates or other implementation)?

Thanks for your help.

**Comment by shamatar** [comment]
Hello @CrisESC93 

I've added extra field to enum of the value notYetProcessed to indicate receipt of transactions not yet included in a chain or with missing "status".

In general event loop is planned for 0.4 version, but for other purposes, such as contract/logs/transaction monitoring and setting delegates for particular events. Such monitoring will allow you to see transaction being included in a block. Otherwise the framework was explicitly made synchronous and all UI and logic details are up to the developer to implement.

Sincerely, Alex

**Comment by CrisESC93** [comment]
Thanks for the help, for now I will create some delegates for the asynchronous side, while I waiting for the release of the 0.4 version.
